import { GameStatsType, GameType } from "../types"

export const MOCK_TEAM_NAME = 'Raptors'
export const MOCK_GAME_STATS: GameStatsType[] = [
 {
  id: 123,
  ast: 10,
  blk: 12,
  dreb: 5,
  fg3_pct: 45,
  fg3a: 6,
  fg3m: 4,
  fg_pct: 34,
  fga: 12,
  fgm: 21,
  ft_pct: 54,
  fta: 2,
  ftm: 34,
  game: {
   id: 23,
   date: '2021-06-23',
   home_team: {
    id: 123,
    abbreviation: 'TOR',
    city: 'Toronto',
    conference: 'Eastern',
    division: 'foobar',
    full_name: 'Toronto Raptors',
    name: 'foorbarbaz',
   },
   home_team_score: 88,
   period: 23,
   postseason: false,
   season: 2020,
   status: 'final',
   time: '12:23am',
   visitor_team: {
    id: 123,
    abbreviation: 'BOS',
    city: 'Boston',
    conference: 'Eastern',
    division: 'foobar',
    full_name: 'Boston Celtics',
    name: 'doobar',
   },
   visitor_team_score: 69,
  },
  min: '25',
  oreb: '23',
  pf: '3',
  player: {
   id: 123,
   first_name: 'Carol',
   height_feet: 7,
   height_inches: 10,
   last_name: 'Pham',
   position: 'Center',
   team_id: 12,
   weight_pounds: 123,
  },
  pts: 123,
  reb: 23,
  stl: 4,
  team: {
   id: 12,
   abbreviation: 'TOR',
   city: 'Toronto',
   conference: 'Eastern',
   division: 'East',
   full_name: 'Toronto Raptors',
   name: 'foooo'
  },
  turnover: 5,
 },
 {
  id: 124,
  ast: 10,
  blk: 12,
  dreb: 5,
  fg3_pct: 45,
  fg3a: 6,
  fg3m: 4,
  fg_pct: 34,
  fga: 12,
  fgm: 21,
  ft_pct: 54,
  fta: 2,
  ftm: 34,
  game: {
   id: 23,
   date: '2021-06-23',
   home_team: {
    id: 123,
    abbreviation: 'TOR',
    city: 'Toronto',
    conference: 'Eastern',
    division: 'foobar',
    full_name: 'Toronto Raptors',
    name: 'foorbarbaz',
   },
   home_team_score: 88,
   period: 23,
   postseason: false,
   season: 2020,
   status: 'final',
   time: '12:23am',
   visitor_team: {
    id: 121,
    abbreviation: 'BOS',
    city: 'Boston',
    conference: 'Eastern',
    division: 'foobar',
    full_name: 'Boston Celtics',
    name: 'doobar',
   },
   visitor_team_score: 69,
  },
  min: '25',
  oreb: '23',
  pf: '3',
  player: {
   id: 123,
   first_name: 'Carol',
   height_feet: 7,
   height_inches: 10,
   last_name: 'Pham',
   position: 'Center',
   team_id: 12,
   weight_pounds: 123,
  },
  pts: 200,
  reb: 23,
  stl: 4,
  team: {
   id: 12,
   abbreviation: 'TOR',
   city: 'Toronto',
   conference: 'Eastern',
   division: 'East',
   full_name: 'Toronto Raptors',
   name: 'Raptors'
  },
  turnover: 5,
 },
 {
  id: 123,
  ast: 10,
  blk: 12,
  dreb: 5,
  fg3_pct: 45,
  fg3a: 6,
  fg3m: 4,
  fg_pct: 34,
  fga: 12,
  fgm: 21,
  ft_pct: 54,
  fta: 2,
  ftm: 34,
  game: {
   id: 23,
   date: '2021-06-23',
   home_team: {
    id: 123,
    abbreviation: 'TOR',
    city: 'Toronto',
    conference: 'Eastern',
    division: 'foobar',
    full_name: 'Toronto Raptors',
    name: 'foorbarbaz',
   },
   home_team_score: 88,
   period: 23,
   postseason: false,
   season: 2020,
   status: 'final',
   time: '12:23am',
   visitor_team: {
    id: 123,
    abbreviation: 'BOS',
    city: 'Boston',
    conference: 'Eastern',
    division: 'foobar',
    full_name: 'Boston Celtics',
    name: 'doobar',
   },
   visitor_team_score: 69,
  },
  min: '25',
  oreb: '23',
  pf: '3',
  player: {
   id: 123,
   first_name: 'Carol',
   height_feet: 7,
   height_inches: 10,
   last_name: 'Pham',
   position: 'Center',
   team_id: 12,
   weight_pounds: 123,
  },
  pts: 123,
  reb: 23,
  stl: 4,
  team: {
   id: 12,
   abbreviation: 'TOR',
   city: 'Toronto',
   conference: 'Eastern',
   division: 'East',
   full_name: 'Toronto Raptors',
   name: 'foooo'
  },
  turnover: 5,
 },
 {
  id: 125,
  ast: 10,
  blk: 12,
  dreb: 5,
  fg3_pct: 45,
  fg3a: 6,
  fg3m: 4,
  fg_pct: 34,
  fga: 12,
  fgm: 21,
  ft_pct: 54,
  fta: 2,
  ftm: 34,
  game: {
   id: 23,
   date: '2021-06-23',
   home_team: {
    id: 123,
    abbreviation: 'TOR',
    city: 'Toronto',
    conference: 'Eastern',
    division: 'foobar',
    full_name: 'Toronto Raptors',
    name: 'foorbarbaz',
   },
   home_team_score: 88,
   period: 23,
   postseason: false,
   season: 2020,
   status: 'final',
   time: '12:23am',
   visitor_team: {
    id: 123,
    abbreviation: 'BOS',
    city: 'Boston',
    conference: 'Eastern',
    division: 'foobar',
    full_name: 'Boston Celtics',
    name: 'doobar',
   },
   visitor_team_score: 69,
  },
  min: '25',
  oreb: '23',
  pf: '3',
  player: {
   id: 123,
   first_name: 'Ellie',
   height_feet: 7,
   height_inches: 10,
   last_name: 'Truong',
   position: 'Center',
   team_id: 12,
   weight_pounds: 123,
  },
  pts: 201,
  reb: 23,
  stl: 4,
  team: {
   id: 12,
   abbreviation: 'TOR',
   city: 'Toronto',
   conference: 'Eastern',
   division: 'East',
   full_name: 'Toronto Raptors',
   name: 'Raptors'
  },
  turnover: 5,
 },
]

export const MOCK_TODAYS_GAME: GameType[] = [
  {
    id: 474119,
    date: "2022-01-24T00:00:00.000Z",
    home_team_score: 0,
    period: 0,
    postseason: false,
    season: 2021,
    status: "8:00 PM ET",
    time: "",
    visitor_team_score: 0,
    home_team: {
      id: 19,
      abbreviation: "NOP",
      city: "New Orleans",
      conference: "West",
      division: "Southwest",
      full_name: "New Orleans Pelicans",
      name: "Pelicans"
    },
    visitor_team: {
      id: 12,
      abbreviation: "IND",
      city: "Indiana",
      conference: "East",
      division: "Central",
      full_name: "Indiana Pacers",
      name: "Pacers"
    },
  },
  {
    id: 474121,
    date: "2022-01-24T00:00:00.000Z",
    home_team_score: 0,
    period: 0,
    postseason: false,
    season: 2021,
    status: "7:30 PM ET",
    time: "",
    home_team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks"
    },
    visitor_team_score: 0,
    visitor_team: {
      id: 5,
      abbreviation: "CHI",
      city: "Chicago",
      conference: "East",
      division: "Central",
      full_name: "Chicago Bulls",
      name: "Bulls"
    },
  }
]