/* istanbul ignore file */
export const teamLogos = [
 { name: 'Hawks', src: 'http://loodibee.com/wp-content/uploads/nba-atlanta-hawks-logo-300x300.png' },
 { name: 'Celtics', src: 'http://loodibee.com/wp-content/uploads/nba-boston-celtics-logo-300x300.png' },
 { name: 'Nets', src: 'http://loodibee.com/wp-content/uploads/nba-brooklyn-nets-logo-300x300.png' },
 { name: 'Hornets', src: 'http://loodibee.com/wp-content/uploads/nba-charlotte-hornets-logo-300x300.png' },
 { name: 'Bulls', src: 'http://loodibee.com/wp-content/uploads/nba-chicago-bulls-logo-300x300.png' },
 { name: 'Cavaliers', src: 'http://loodibee.com/wp-content/uploads/nba-cleveland-cavaliers-logo-300x300.png' },
 { name: 'Mavericks', src: 'http://loodibee.com/wp-content/uploads/nba-dallas-mavericks-logo-300x300.png' },
 { name: 'Nuggets', src: 'http://loodibee.com/wp-content/uploads/nba-denver-nuggets-logo-2018-300x300.png' },
 { name: 'Pistons', src: 'http://loodibee.com/wp-content/uploads/nba-detroit-pistons-logo-300x300.png' },
 { name: 'Warriors', src: 'http://loodibee.com/wp-content/uploads/nba-golden-state-warriors-logo-2020-300x300.png' },
 { name: 'Rockets', src: 'http://loodibee.com/wp-content/uploads/nba-houston-rockets-logo-2020-300x300.png' },
 { name: 'Pacers', src: 'http://loodibee.com/wp-content/uploads/nba-indiana-pacers-logo-300x300.png' },
 { name: 'Clippers', src: 'http://loodibee.com/wp-content/uploads/nba-la-clippers-logo-300x300.png' },
 { name: 'Lakers', src: 'http://loodibee.com/wp-content/uploads/nba-los-angeles-lakers-logo-300x300.png' },
 { name: 'Grizzlies', src: 'http://loodibee.com/wp-content/uploads/nba-memphis-grizzlies-logo-300x300.png' },
 { name: 'Heat', src: 'http://loodibee.com/wp-content/uploads/nba-miami-heat-logo-300x300.png' },
 { name: 'Bucks', src: 'http://loodibee.com/wp-content/uploads/nba-milwaukee-bucks-logo-300x300.png' },
 { name: 'Timberwolves', src: 'http://loodibee.com/wp-content/uploads/nba-minnesota-timberwolves-logo-300x300.png' },
 { name: 'Pelicans', src: 'http://loodibee.com/wp-content/uploads/nba-new-orleans-pelicans-logo-300x300.png' },
 { name: 'Knicks', src: 'http://loodibee.com/wp-content/uploads/nba-new-york-knicks-logo-300x300.png' },
 { name: 'Thunder', src: 'http://loodibee.com/wp-content/uploads/nba-oklahoma-city-thunder-logo-300x300.png' },
 { name: 'Magic', src: 'http://loodibee.com/wp-content/uploads/nba-orlando-magic-logo-300x300.png' },
 { name: '76ers', src: 'http://loodibee.com/wp-content/uploads/nba-philadelphia-76ers-logo-300x300.png' },
 { name: 'Suns', src: 'http://loodibee.com/wp-content/uploads/nba-phoenix-suns-logo-300x300.png' },
 { name: 'Trail Blazers', src: 'http://loodibee.com/wp-content/uploads/nba-portland-trail-blazers-logo-300x300.png' },
 { name: 'Kings', src: 'http://loodibee.com/wp-content/uploads/nba-sacramento-kings-logo-300x300.png' },
 { name: 'Spurs', src: 'http://loodibee.com/wp-content/uploads/nba-san-antonio-spurs-logo-300x300.png' },
 { name: 'Raptors', src: 'http://loodibee.com/wp-content/uploads/nba-toronto-raptors-logo-2020-300x300.png' },
 { name: 'Wizards', src: 'http://loodibee.com/wp-content/uploads/nba-washington-wizards-logo-300x300.png' },
 { name: 'Jazz', src: 'http://loodibee.com/wp-content/uploads/nba-utah-jazz-logo-300x300.png' },
]